---
title: "Run statistics 2 (rs2)"
author: "Anastasis Giannousakis"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Run statistics 2 (rs2)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

The `rs2` tool gives you quick, easy, and handy access to a number of info and statistics (status, type, convergence, reporting, etc. -- the list is extended continuously) for your model runs. This document provides a short tutorial on how to make the most out of `rs2`. 

## 5 common use cases:

1. You want a quick overview of all your recent jobs (_regardless where they are_):
`rs2 -c`
If you want to do the same for the jobs of someone else (can also be `user1,user2` for multiple users):
`rs2 -c username`
If you want to adjust the number of days that the tool reports jobs for:
`rs2 -c [username] 10`
e.g. for 10 days back.

2. You want a quick overview of all jobs in slurm
`rs2 -a [username]`

3. You go into a run folder (e.g. by using `cdf`) and want to see its status:
```rs2 .```

4. You are in an `output` folder containing many run folders and want to see their status (or of some of them):
`rs2`
and then filter by pattern, e.g. `^C_` for all coupled runs, or `03-25` for all runs on Mar 25

5. You are in a hurry and want to see immediately what is going on in the run folders of your current directory:
`rs2 -f`

6. You want to collect information about your runs and store/process it in R:
`modelstats::getRunStatus()`
returns a data.frame with the job information.
