"""Coexistence matrix of plan 03 section 2.3 (marker ``golden``): R and Python AMT cycles alternating on one tree.

Every scenario is one ``migration/harness/sandbox.sh`` invocation (read-only fixture overlay, stopped clock, fake
scheduler / git / sbatch / make / Rscript-start binaries, the ``remind-evaluate`` canned outputs) whose command is a
generated ``/bin/sh`` script that runs the steps in sequence on the same overlay: the R side as ``Rscript -e
'devtools::load_all(<worktree>); modeltests(...)'`` (with ``Sys.sleep`` replaced by a no-op as ``make_goldens.R``
does, the stopped clock would never release it), the Python side as the installed ``modeltests`` console script of
the worktree's ``.venv`` (production Effects, no token: the notification path is covered by the 46 amt goldens).
The start steps run at ``2026-09-28 12:00:00`` so that the runcode they write names the fixture runs
(``*-AMT_2026-09-28_*``), the evaluate steps at the default ``2026-09-30 12:00:00``; ``FAKETIME`` is re-read per
process. The starting state is the ``remind-evaluate`` prepare script (``next:evaluate``, the gRS history trimmed to
runs with a ``runstatistics.rda`` in the snapshot) plus the scenario's own prepare script.

After every step the script records the exit status, stdout and stderr (``/out/<step>.*``), and a ``snapshot``
records the sha256 of the four state files, ``.testsstatus`` and ``dump_state.R``'s R reading of every state file
(class, row names, values: a file the other implementation cannot read would show as ``read_error``).

Scenarios (the matrix of 03 section 2.3):

1. R start, Python evaluate;
2. Python start, R evaluate;
3. a full Python cycle, then an R cycle (the rollback), then a Python cycle again;
4. an interrupted Python evaluate (SIGKILL once the analysis has begun): the three cycle state files are byte-identical
   to the pre-cycle state, ``.testsstatus`` holds R's running marker, ``gRS.rds`` is complete and R-readable, no
   temporary file is left behind, and the R evaluate then completes on that state after the operator resets
   ``.testsstatus``;
5. a partial write (a writer's temporary file left beside ``gRS.rds`` and ``lastcommit.rds``): both implementations
   ignore it and complete; the file stays (neither removes it);
6. a corrupt state file (``gRS.rds`` / ``lastcommit.rds`` replaced by garbage): both fail with R's ``unknown input
   format``, leave ``.testsstatus`` at the running marker and the other state files untouched, identically.

Skipped with a reason when the sandbox cannot run here (no ``migration/`` tree, ``bwrap``, ``Rscript`` or
``.venv/bin/modeltests``); the conftest skips the whole golden tier without the fixture tree. Nothing else skips.
The case directories are kept under ``migration/_scratch/coexistence/<scenario>/`` as evidence.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

import pytest

pytestmark = pytest.mark.golden

REPO = Path(__file__).resolve().parents[2]
MIGRATION = REPO / "migration"
SANDBOX = MIGRATION / "harness" / "sandbox.sh"
DUMP_STATE_IN = "/opt/harness/dump_state.R"
CASES = MIGRATION / "cases" / "amt"
SCRATCH = MIGRATION / "_scratch" / "coexistence"
MODELTESTS_BIN = REPO / ".venv" / "bin" / "modeltests"
SANDBOX_TIMEOUT = 1800

MYDIR = "/p/projects/remind/modeltests/remind/"
GITDIR = "/p/projects/remind/modeltests/testing_suite"
STATUS_FILE = "/p/projects/remind/modeltests/.testsstatus"
STATE_FILES = ("lastcommit.rds", "runcode.rds", "runsToStart.rds", "output/gRS.rds")
START_TIME = "2026-09-28 12:00:00"
EVAL_TIME = "2026-09-30 12:00:00"
RUNNING = "evaluateRuns() is running or stopped due to an error"
EVALUATE_FINISHED = "Function 'evaluateRuns' finished."
START_FINISHED = "Function 'startRuns' finished."
ANALYSIS_MARKER = "Starting analysis for the list of the following runs:"
UNKNOWN_FORMAT = "unknown input format"

R_CALL = (
    'unlockBinding("Sys.sleep", baseenv()); assign("Sys.sleep", function(time) invisible(NULL), envir = baseenv()); '
    'lockBinding("Sys.sleep", baseenv()); '
    'suppressMessages(devtools::load_all(Sys.getenv("MODELSTATS_REPO"), quiet = TRUE, compile = FALSE)); '
    f'modeltests(mydir = "{MYDIR}", gitdir = "{GITDIR}", model = "REMIND", user = "pascalfu", email = FALSE, '
    "compScen = TRUE, mattermostToken = NULL)"
)

PRELUDE = f"""#!/bin/sh
# generated by tests/golden/test_amt_coexistence.py; runs inside sandbox.sh
set -u
PY="$MODELSTATS_REPO/.venv/bin/modeltests"
r_step() {{  # r_step NAME FAKETIME
  FAKETIME="$2" Rscript -e '{R_CALL}' > "/out/$1.out" 2> "/out/$1.err"
  echo $? > "/out/$1.status"
}}
py_step() {{  # py_step NAME FAKETIME
  FAKETIME="$2" "$PY" --mydir {MYDIR} --gitdir {GITDIR} --model REMIND --user pascalfu --no-email --comp-scen \\
    > "/out/$1.out" 2> "/out/$1.err"
  echo $? > "/out/$1.status"
}}
interrupt_py_step() {{  # interrupt_py_step NAME FAKETIME MARKER: SIGKILL once MARKER shows on stderr
  FAKETIME="$2" "$PY" --mydir {MYDIR} --gitdir {GITDIR} --model REMIND --user pascalfu --no-email --comp-scen \\
    > "/out/$1.out" 2> "/out/$1.err" &
  pid=$!; killed=0; n=0
  while kill -0 "$pid" 2>/dev/null; do
    if grep -q "$3" "/out/$1.err" 2>/dev/null; then kill -KILL "$pid"; killed=1; break; fi
    n=$((n + 1)); [ "$n" -gt 12000 ] && break
    sleep 0.05
  done
  wait "$pid"; echo $? > "/out/$1.status"; echo "$killed" > "/out/$1.killed"
}}
snapshot() {{  # snapshot NAME: state hashes, .testsstatus, R's reading of every state file, leftover temp files
  mkdir -p "/out/$1"
  for f in {" ".join(STATE_FILES)}; do
    (cd {MYDIR} && sha256sum "$f" 2>/dev/null || echo "missing  $f") >> "/out/$1/sha256.txt"
    j="/out/$1/$(echo "$f" | sed 's#[/.][/.]*#_#g').json"
    Rscript {DUMP_STATE_IN} "{MYDIR}$f" "$j" "$f" >> "/out/$1/dump.log" 2>&1
  done
  cat {STATUS_FILE} > "/out/$1/testsstatus" 2>/dev/null || echo "<missing>" > "/out/$1/testsstatus"
  (ls -a {MYDIR} {MYDIR}output | grep '\\.tmp$' || true) > "/out/$1/tmpfiles.txt"
}}
set_status() {{ echo "$1" > {STATUS_FILE}; }}
"""


@dataclass(frozen=True)
class Snapshot:
    """One ``snapshot NAME`` of the generated script, read back from ``/out/NAME``."""

    hashes: dict[str, str]
    testsstatus: str
    dumps: dict[str, dict[str, object]]
    tmpfiles: list[str]

    def readable(self, name: str) -> bool:
        return bool(self.dumps[name].get("exists")) and "read_error" not in self.dumps[name]


@dataclass(frozen=True)
class Run:
    """The result of one sandbox invocation."""

    out: Path
    status: int

    def step_status(self, name: str) -> int:
        return int((self.out / f"{name}.status").read_text().strip())

    def step_err(self, name: str) -> str:
        return (self.out / f"{name}.err").read_text(encoding="utf-8", errors="replace")

    def snapshot(self, name: str) -> Snapshot:
        root = self.out / name
        hashes: dict[str, str] = {}
        for line in (root / "sha256.txt").read_text().splitlines():
            digest, _, path = line.partition("  ")
            hashes[path] = digest
        dumps = {p.name: json.loads(p.read_text(encoding="utf-8")) for p in sorted(root.glob("*.json"))}
        tmpfiles = [line for line in (root / "tmpfiles.txt").read_text().splitlines() if line.strip()]
        return Snapshot(hashes, (root / "testsstatus").read_text().strip(), dumps, tmpfiles)


def _sandbox_available() -> str | None:
    """The reason the sandbox cannot run here, or ``None``."""
    if not SANDBOX.is_file():
        return f"{SANDBOX} is missing"
    if not (MIGRATION / "fixtures" / "p" / "projects").is_dir():
        return "the fixture tree migration/fixtures/p/projects is absent"
    if not (CASES / "remind-evaluate" / "prepare.sh").is_file():
        return "the amt case remind-evaluate is absent"
    if not MODELTESTS_BIN.is_file():
        return f"{MODELTESTS_BIN} is missing (run 'uv sync')"
    for tool in ("bwrap", "Rscript"):
        if shutil.which(tool) is None:
            return f"{tool} is not installed"
    return None


def run_scenario(name: str, prepare: str, steps: str) -> Run:
    """Run one scenario in the sandbox: ``prepare`` (sh, cwd = fixture root) then ``steps`` (sh, after PRELUDE)."""
    reason = _sandbox_available()
    if reason is not None:
        pytest.skip(f"coexistence scenario {name} skipped: {reason}")
    case_dir = SCRATCH / name
    shutil.rmtree(case_dir, ignore_errors=True)
    scripts = case_dir / "scripts"
    scripts.mkdir(parents=True)
    (scripts / "coexist-prepare.sh").write_text("#!/bin/sh\nset -e\n" + prepare, encoding="utf-8")
    (scripts / "steps.sh").write_text(PRELUDE + steps, encoding="utf-8")
    cmd = [
        str(SANDBOX),
        str(case_dir),
        "--mode",
        "oncluster",
        "--amt-case",
        "remind-evaluate",
        "--frozen",
        EVAL_TIME,
        "--prepare",
        str(CASES / "remind-evaluate" / "prepare.sh"),
        "--prepare",
        str(scripts / "coexist-prepare.sh"),
        "--bind-ro",
        f"{scripts}:/opt/coexist",
        "--env",
        "PYTHONDONTWRITEBYTECODE=1",
        "--",
        "/bin/sh",
        "/opt/coexist/steps.sh",
    ]
    log = case_dir / "sandbox.log"
    with log.open("wb") as handle:
        proc = subprocess.run(
            cmd, cwd=REPO, stdout=handle, stderr=subprocess.STDOUT, timeout=SANDBOX_TIMEOUT, check=False
        )
    if not (case_dir / "out" / "status").is_file():
        pytest.fail(f"{name}: the sandbox did not run the steps (status {proc.returncode}); see {log}")
    return Run(case_dir / "out", proc.returncode)


def assert_step_ok(run: Run, step: str, finished: str) -> None:
    err = run.step_err(step)
    assert run.step_status(step) == 0, f"{step} failed (status {run.step_status(step)}):\n{err[-3000:]}"
    assert finished in err, f"{step}: '{finished}' missing from stderr:\n{err[-3000:]}"


def _rows(dump: dict[str, object]) -> list[dict[str, object]]:
    """The ``rows`` of a data.frame state dump (``{"value": {"rows": [...]}}``)."""
    value = dump.get("value")
    assert isinstance(value, dict) and isinstance(value.get("rows"), list), dump
    return [dict(row) for row in value["rows"]]


def assert_state_readable(snap: Snapshot, *names: str) -> None:
    for name in names:
        assert snap.readable(name), f"{name}: not readable by R: {snap.dumps[name]}"


# ---------------------------------------------------------------------------
# the scenarios
# ---------------------------------------------------------------------------


def test_r_start_then_python_evaluate() -> None:
    run = run_scenario(
        "r-start-py-evaluate",
        f"echo next:start > {STATUS_FILE}\n",
        f"""snapshot pre
r_step r_start '{START_TIME}'
snapshot after_r_start
py_step py_evaluate '{EVAL_TIME}'
snapshot after_py_evaluate
""",
    )
    assert run.status == 0
    assert_step_ok(run, "r_start", START_FINISHED)
    after_start = run.snapshot("after_r_start")
    assert after_start.testsstatus == "next:evaluate"
    assert_step_ok(run, "py_evaluate", EVALUATE_FINISHED)
    after = run.snapshot("after_py_evaluate")
    assert after.testsstatus == "next:start"
    # the Python evaluate read R's runsToStart.rds and runcode.rds (unchanged by it) and wrote the rest
    assert after.hashes["runsToStart.rds"] == after_start.hashes["runsToStart.rds"]
    assert after.hashes["runcode.rds"] == after_start.hashes["runcode.rds"]
    assert after.hashes["lastcommit.rds"] != after_start.hashes["lastcommit.rds"]
    assert_state_readable(
        after, "lastcommit_rds.json", "runcode_rds.json", "runsToStart_rds.json", "output_gRS_rds.json"
    )
    assert after.dumps["lastcommit_rds.json"]["value"] == ["3f5e2a1b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f"]
    assert after.dumps["runcode_rds.json"]["value"] == [".*-AMT_2026-09-28|.*-AMT_2026-09-29"]
    assert after.tmpfiles == []


def test_python_start_then_r_evaluate() -> None:
    run = run_scenario(
        "py-start-r-evaluate",
        f"echo next:start > {STATUS_FILE}\n",
        f"""snapshot pre
py_step py_start '{START_TIME}'
snapshot after_py_start
r_step r_evaluate '{EVAL_TIME}'
snapshot after_r_evaluate
""",
    )
    assert run.status == 0
    assert_step_ok(run, "py_start", START_FINISHED)
    after_start = run.snapshot("after_py_start")
    assert after_start.testsstatus == "next:evaluate"
    assert_state_readable(after_start, "runcode_rds.json", "runsToStart_rds.json")
    assert after_start.dumps["runcode_rds.json"]["value"] == [".*-AMT_2026-09-28|.*-AMT_2026-09-29"]
    rows = _rows(after_start.dumps["runsToStart_rds.json"])
    assert rows and all(str(row["_row"]).endswith("-AMT") for row in rows)
    assert_step_ok(run, "r_evaluate", EVALUATE_FINISHED)
    after = run.snapshot("after_r_evaluate")
    assert after.testsstatus == "next:start"
    assert after.hashes["runsToStart.rds"] == after_start.hashes["runsToStart.rds"]
    assert after.hashes["lastcommit.rds"] != after_start.hashes["lastcommit.rds"]
    assert_state_readable(after, "lastcommit_rds.json", "output_gRS_rds.json")
    assert after.tmpfiles == []


def test_python_cycle_r_cycle_python_cycle() -> None:
    steps = "snapshot pre\n"
    plan = [
        ("py_start_1", "py_step", START_TIME),
        ("py_evaluate_1", "py_step", EVAL_TIME),
        ("r_start_2", "r_step", START_TIME),
        ("r_evaluate_2", "r_step", EVAL_TIME),
        ("py_start_3", "py_step", START_TIME),
        ("py_evaluate_3", "py_step", EVAL_TIME),
    ]
    for name, fn, when in plan:
        steps += f"{fn} {name} '{when}'\nsnapshot after_{name}\n"
    run = run_scenario("py-r-py-cycles", f"echo next:start > {STATUS_FILE}\n", steps)
    assert run.status == 0
    for name, _fn, _when in plan:
        finished = START_FINISHED if "start" in name else EVALUATE_FINISHED
        assert_step_ok(run, name, finished)
        snap = run.snapshot(f"after_{name}")
        assert snap.testsstatus == ("next:evaluate" if "start" in name else "next:start"), name
        assert_state_readable(
            snap, "lastcommit_rds.json", "runcode_rds.json", "runsToStart_rds.json", "output_gRS_rds.json"
        )
        assert snap.tmpfiles == [], name
    # the gRS history keeps its rows across the three writers (R's rbind on the Python table and back)
    names = [
        {str(row["_row"]) for row in _rows(run.snapshot(f"after_{name}").dumps["output_gRS_rds.json"])}
        for name in ("py_evaluate_1", "r_evaluate_2", "py_evaluate_3")
    ]
    assert names[0] <= names[1] <= names[2], names


def test_interrupted_python_evaluate_leaves_the_pre_cycle_state() -> None:
    run = run_scenario(
        "interrupted-py-evaluate",
        "true\n",
        f"""snapshot pre
interrupt_py_step py_evaluate '{EVAL_TIME}' '{ANALYSIS_MARKER}'
snapshot after_interrupt
set_status next:evaluate
r_step r_evaluate '{EVAL_TIME}'
snapshot after_r_evaluate
""",
    )
    assert run.status == 0
    assert (run.out / "py_evaluate.killed").read_text().strip() == "1", "the evaluate was not interrupted"
    err = run.step_err("py_evaluate")
    assert ANALYSIS_MARKER in err and EVALUATE_FINISHED not in err
    pre, after = run.snapshot("pre"), run.snapshot("after_interrupt")
    for name in ("lastcommit.rds", "runcode.rds", "runsToStart.rds"):
        assert after.hashes[name] == pre.hashes[name], name
    assert after.testsstatus == RUNNING
    assert_state_readable(after, "output_gRS_rds.json")
    assert after.dumps["output_gRS_rds.json"]["class"] == "data.frame"  # jsonlite auto_unbox: a scalar
    assert after.tmpfiles == []
    # the R rollback resumes from that state once the operator resets the marker
    assert_step_ok(run, "r_evaluate", EVALUATE_FINISHED)
    final = run.snapshot("after_r_evaluate")
    assert final.testsstatus == "next:start"
    assert final.hashes["lastcommit.rds"] != pre.hashes["lastcommit.rds"]


def test_partial_write_temp_file_left_behind_is_ignored_by_both() -> None:
    temp_files = (f"{MYDIR}output/.gRS.rds.0123456789ab.tmp", f"{MYDIR}.lastcommit.rds.0123456789ab.tmp")
    prepare = "".join(f"printf 'partial write' > {p}\n" for p in temp_files)
    run = run_scenario(
        "partial-write",
        prepare,
        f"""snapshot pre
py_step py_evaluate '{EVAL_TIME}'
snapshot after_py_evaluate
set_status next:evaluate
r_step r_evaluate '{EVAL_TIME}'
snapshot after_r_evaluate
""",
    )
    assert run.status == 0
    assert sorted(run.snapshot("pre").tmpfiles) == sorted(Path(p).name for p in temp_files)
    assert_step_ok(run, "py_evaluate", EVALUATE_FINISHED)
    after_py = run.snapshot("after_py_evaluate")
    assert after_py.testsstatus == "next:start"
    assert_state_readable(after_py, "lastcommit_rds.json", "output_gRS_rds.json")
    assert sorted(after_py.tmpfiles) == sorted(Path(p).name for p in temp_files)
    assert_step_ok(run, "r_evaluate", EVALUATE_FINISHED)
    after_r = run.snapshot("after_r_evaluate")
    assert after_r.testsstatus == "next:start"
    assert_state_readable(after_r, "lastcommit_rds.json", "output_gRS_rds.json")
    assert sorted(after_r.tmpfiles) == sorted(Path(p).name for p in temp_files)


@pytest.mark.parametrize("corrupt", ["output/gRS.rds", "lastcommit.rds"])
def test_corrupt_state_file_fails_identically(corrupt: str) -> None:
    tag = corrupt.replace("/", "-").replace(".", "-")
    run = run_scenario(
        f"corrupt-{tag}",
        f"echo garbage > {MYDIR}{corrupt}\n",
        f"""snapshot pre
py_step py_evaluate '{EVAL_TIME}'
snapshot after_py_evaluate
set_status next:evaluate
r_step r_evaluate '{EVAL_TIME}'
snapshot after_r_evaluate
""",
    )
    assert run.status == 0
    pre = run.snapshot("pre")
    for step, snap_name in (("py_evaluate", "after_py_evaluate"), ("r_evaluate", "after_r_evaluate")):
        assert run.step_status(step) == 1, f"{step}: status {run.step_status(step)}\n{run.step_err(step)[-2000:]}"
        assert UNKNOWN_FORMAT in run.step_err(step), f"{step}: R's error text missing\n{run.step_err(step)[-2000:]}"
        assert "Execution halted" in run.step_err(step)
        snap = run.snapshot(snap_name)
        assert snap.testsstatus == RUNNING, step
        for name in ("lastcommit.rds", "runcode.rds", "runsToStart.rds"):
            assert snap.hashes[name] == pre.hashes[name], f"{step}: {name} changed"
        assert snap.tmpfiles == [], step
    # both implementations left the same tree behind (the corrupt file included: neither rewrote it)
    after_py, after_r = run.snapshot("after_py_evaluate"), run.snapshot("after_r_evaluate")
    assert after_py.hashes == after_r.hashes == pre.hashes
    assert after_py.testsstatus == after_r.testsstatus
